### ISSUE TITLE
HELP! Cannot get into your note

### ISSUE THREAD

**Issue by ppap36** [yaswanth1701/Trajectory-Optimization#1]
**problem description**
In your Notes in Reference
When I open it, it shows that your note is missing or I have no permission

can anyone help me?
Thanks

**Comment by ppap36** [comment]
Oh, I found another bug, the mesh file in your rrr_arm.urdf is missing! Where are they?

**Comment by yaswanth1701** [comment]
Hi there, thanks for reaching out, and sorry for the trouble, I was in a hurry while I was adding the link and it might have ended up being private only. Here is the [new link](https://yaswanth-gonna.notion.site/Trajectory-Optimisation-DDP-iLQR-7b680055afff496ba324bc03827f32e3).  One thing the notes aren't fully complete, while I was working on this repo I didn't consider that it might end up getting stars or issue raised by other people as it was just my hobby project. A few commits are left to be pushed from my local repo which contains your mentioned files.

**Comment by yaswanth1701** [comment]
I am not able to work on this project given the time constraints. However, I am considering completing the notes for all the things I have implemented till now, let me which part of this project you want to see first (I will work on it this weekend) in the notes which are missing.

**Comment by yaswanth1701** [comment]
One last thing if you want a detailed explanation for most of the optimal control stuff, you can refer to [Optimal Control by Zachary Manchester ](https://github.com/Optimal-Control-16-745/) highly recommended. I am always open to discussion about optimal control and robotics so, please feel free to tag me when ever you want.

**Comment by ppap36** [comment]
thank you so much!!!!

**Comment by ppap36** [comment]
Maybe you can complete the manipulator's mesh file.
I have ran your cartpole perfectly, It ran well
And I want to check the manipulator's result

**Comment by yaswanth1701** [comment]
I will update these files tonight and let you know once I'm done.

**Comment by yaswanth1701** [comment]
Hi @ppap36, the issue with urdf is fixed, you can try running it on your side and let me know if you face any problems. After pulling updates from the remote, use `git submodule update --init --recursive`.  Also, to run cart pole iLQR you have to make changes to classical control gym library files as there are some constraints on the states of the cart pole by default which need to be removed for nonlinear stuff. I will update those tomorrow.

**Comment by ppap36** [comment]
Great! I have tried it and the 3 python files goes well, except the  `3R_manipulator.py`
but I think it is not necessary to fix that because it doesn't have much content.

My tutor recommend me to learn your project, you are famous in our laboratory
Thank you so much!

**Comment by yaswanth1701** [comment]
That's great, the files you mentioned weren't supposed to be there I removed all the unnecessary ones in my recent commits.

**Comment by ppap36** [comment]
sorry to bother you, my friend.
Did you take notes when deploying ilqr on the manipulator?
If so, could you do a favor to share it?
Thank you very much

**Comment by yaswanth1701** [comment]
No, I haven't however it's simple to I will try to summarise this here.

-  So, I did trajectory optimisation in joint space. Using inverse kinematics we can get the joint angle required for desired configuration (position and orientation) 
- we need to calculate the mass Matrix (function of position only) and non linear terms (function of both position and velocity) to get the joint acceleration given joint torque which are coming from optimisation.
-  Calculation of mass matrix and non linear terms( centrifugal, corroliss and gravity) can be easily done. Pybullet provides this functionality ( [here](https://github.com/bulletphysics/bullet3/discussions/3746) ) or one can open source libraries like Pinocchio for this. 
- Once we have joint acceleration one can use numerical integrator (Euler/rk4) to get the next state (position and velocity). 
- For calculation of gradient vector and hessian of cost I use Central difference method and same goes for jacobain of dynamics which I think I mentioned in notes. 
- Rest of algorithm is same.

I hope this helps, I try to write this in notes in a more detailed matter however in the due time you can refer to this blog on iLQR which I think might help ([here](https://studywolf.wordpress.com/2016/02/03/the-iterative-linear-quadratic-regulator-method/))

**Comment by ppap36** [comment]
I almost got your code's idea
However, I suddenly noticed that the final error of the manipulator maybe too huge.(Check picture below)
![Screenshot from 2024-03-06 17-14-01](https://github.com/yaswanth1701/Trajectory-Optimization/assets/108739132/58c399db-a7f0-43df-b7e7-c79b5466c34c)
The 5-th of the final state error is over 1, will it be too huge?

**Comment by yaswanth1701** [comment]
I faced this problem while working with this many times. The best solution to this is to increase the cost for that particular state until you see a good enough performance.

**Comment by yaswanth1701** [comment]
Another issue with traj opt which I faced a lot is the state deviating from the desired state at the end of the horizon in both direction collocation method and iLQR. I think it might be due to some ill-conditioning at the end. You can try removing the last few time step's states and control inputs and see how it works.

**Comment by ppap36** [comment]
When I increase the cost of position, the position error will be less and velocity error will be larger.(obviously)

But why the velocity error didn't effect the pybullet
I suppose it will have too fast speed and exceed the target position

**Comment by yaswanth1701** [comment]
yeah will exceed the desired state with that velocity. but I am running the simulation only for planning horizon length time that's why it's not visible in the pybullet.

**Comment by yaswanth1701** [comment]
I just checked the issue that you mentioned the issue here is that there is no terminal cost incorporated in my code which is general practice in optimal control. So you might see in the plot the velocities are slowly deviating from the desired value in the last 100 - 200 time steps which leads to this error.

**Comment by yaswanth1701** [comment]
![Screenshot from 2024-03-06 15-39-00](https://github.com/yaswanth1701/Trajectory-Optimization/assets/92177410/dad0bc50-24e2-44a8-bcde-44eb2907b628)
![Figure_2](https://github.com/yaswanth1701/Trajectory-Optimization/assets/92177410/631e0f25-c47f-47a0-b5b4-a0004758017f)

**Comment by yaswanth1701** [comment]
these values of Q and R matrix should solve the issue without the terminal cost

**Comment by yaswanth1701** [comment]
as you can see the second joint requires a lot more torque as compared to the rest two. So, for the states to reach properly the cost of the torque should be low.

**Comment by ppap36** [comment]
Great! I knew you didn't have the terminal cost before, but I didn't know it is so important to have the terminal cost.

**Comment by ppap36** [comment]
By the way, I think your code is convenient for beginner and I want to make a video for it on https://www.bilibili.com/
Maybe it can add your stars.
Do you have interest in it?

**Comment by yaswanth1701** [comment]
Yeah sure, that sounds great!!.

by the way, if you don't mind can I know what are working on?

**Comment by yaswanth1701** [comment]
> Great! I knew you didn't have the terminal cost before, but I didn't know it is so important to have the terminal cost.

yeah terminal cost doesn't have the control inputs in it so, it tries to minimize over-state as much as possible which avoids situations like these.

**Comment by ppap36** [comment]
OK! I am a college student. And my reserch field is robot arm.

**Comment by yaswanth1701** [comment]
Ohh I see that's nice, if in case you are using iLQR for MPC my code is very slow for that, from my experience with ROS+MPC you would require at least a node frequency of 10-20hz in the case of turtle bot might be even higher for chaotic dynamics like manipulator arm. I would suggest using direct collocation (with an initial guess) for trajectory optimization instead of this would be much faster.

**Comment by ppap36** [comment]
By the way my dear friend.
When you encounter problems with robotics algorithms, where do you usually search for forums or websites except github?
Do you join some group to ask for questions?
I am a beginner for the [https://leggedrobotics.github.io/ocs2/overview.html](url), which is used for solving optimal control problem. And the ocs2's developer did not have a complete tutorial(You know, just some robot examples, but they don't tell how to use the function or the structure of the code). I can only develop it  by mimicking example code.

**Comment by yaswanth1701** [comment]
Unfortunately, the stuff related to robotics algo is pretty scattered especially optimal control. I previously joined a [discord server](https://discord.gg/vmc6pnQm) for control theory discussion but I haven't used it much, you can give it a try. Apart from this there is [DRAKE](https://drake.mit.edu/) library which has very good tutorials in Python (Prof Russ might reply sometimes to clear doubts). I don't think there are any forums or websites for optimal control that I specifically refer to.

**Comment by yaswanth1701** [comment]
And yeah it's kind of true. Whatever optimal control libraries I have seen till now, all are pretty bad at maintaining documentation on how to use them

**Comment by ppap36** [comment]
hey bro!
I have made a video for your program on bilibili. I hope you will get more stars!
https://www.bilibili.com/video/BV1nK421t7Jg/?vd_source=5d5065c07632b817f1765a8d48bbdb4f

**Comment by yaswanth1701** [comment]
Thank you, it means a lot. I will put the video link in the readme.
